// length 164
const currencies = [
    {label:"Afghan Afghani",value:"AFA",symbol:"؋"},
    {label:"Albanian Lek",value:"ALL",symbol:"Lek"},
    {label:"Algerian Dinar",value:"DZD",symbol:"دج"},
    {label:"Angolan Kwanza",value:"AOA",symbol:"Kz"},
    {label:"Argentine Peso",value:"ARS",symbol:"$"},
    {label:"Armenian Dram",value:"AMD",symbol:"֏"},
    {label:"Aruban Florin",value:"AWG",symbol:"ƒ"},
    {label:"Australian Dollar",value:"AUD",symbol:"$"},
    {label:"Azerbaijani Manat",value:"AZN",symbol:"m"},
    {label:"Bahamian Dollar",value:"BSD",symbol:"B$"},
    {label:"Bahraini Dinar",value:"BHD",symbol:".د.ب"},
    {label:"Bangladeshi Taka",value:"BDT",symbol:"৳"},
    {label:"Barbadian Dollar",value:"BBD",symbol:"Bds$"},
    {label:"Belarusian Ruble",value:"BYR",symbol:"Br"},
    {label:"Belgian Franc",value:"BEF",symbol:"fr"},
    {label:"Belize Dollar",value:"BZD",symbol:"$"},
    {label:"Bermudan Dollar",value:"BMD",symbol:"$"},
    {label:"Bhutanese Ngultrum",value:"BTN",symbol:"Nu."},
    {label:"Bitcoin",value:"BTC",symbol:"฿"},
    {label:"Bolivian Boliviano",value:"BOB",symbol:"Bs."},
    {label:"Bosnia-Herzegovina Convertible Mark",value:"BAM",symbol:"KM"},
    {label:"Botswanan Pula",value:"BWP",symbol:"P"},
    {label:"Brazilian Real",value:"BRL",symbol:"R$"},
    {label:"British Pound Sterling",value:"GBP",symbol:"£"},
    {label:"Brunei Dollar",value:"BND",symbol:"B$"},
    {label:"Bulgarian Lev",value:"BGN",symbol:"Лв."},
    {label:"Burundian Franc",value:"BIF",symbol:"FBu"},
    {label:"Cambodian Riel",value:"KHR",symbol:"KHR"},
    {label:"Canadian Dollar",value:"CAD",symbol:"$"},
    {label:"Cape Verdean Escudo",value:"CVE",symbol:"$"},
    {label:"Cayman Islands Dollar",value:"KYD",symbol:"$"},
    {label:"CFA Franc BCEAO",value:"XOF",symbol:"CFA"},
    {label:"CFA Franc BEAC",value:"XAF",symbol:"FCFA"},
    {label:"CFP Franc",value:"XPF",symbol:"₣"},
    {label:"Chilean Peso",value:"CLP",symbol:"$"},
    {label:"Chinese Yuan",value:"CNY",symbol:"¥"},
    {label:"Colombian Peso",value:"COP",symbol:"$"},
    {label:"Comorian Franc",value:"KMF",symbol:"CF"},
    {label:"Congolese Franc",value:"CDF",symbol:"FC"},
    {label:"Costa Rican ColÃ³n",value:"CRC",symbol:"₡"},
    {label:"Croatian Kuna",value:"HRK",symbol:"kn"},
    {label:"Cuban Convertible Peso",value:"CUC",symbol:"$, CUC"},
    {label:"Czech Republic Koruna",value:"CZK",symbol:"Kč"},
    {label:"Danish Krone",value:"DKK",symbol:"Kr."},
    {label:"Djiboutian Franc",value:"DJF",symbol:"Fdj"},
    {label:"Dominican Peso",value:"DOP",symbol:"$"},
    {label:"East Caribbean Dollar",value:"XCD",symbol:"$"},
    {label:"Egyptian Pound",value:"EGP",symbol:"ج.م"},
    {label:"Eritrean Nakfa",value:"ERN",symbol:"Nfk"},
    {label:"Estonian Kroon",value:"EEK",symbol:"kr"},
    {label:"Ethiopian Birr",value:"ETB",symbol:"Nkf"},
    {label:"Euro",value:"EUR",symbol:"€"},
    {label:"Falkland Islands Pound",value:"FKP",symbol:"£"},
    {label:"Fijian Dollar",value:"FJD",symbol:"FJ$"},
    {label:"Gambian Dalasi",value:"GMD",symbol:"D"},
    {label:"Georgian Lari",value:"GEL",symbol:"ლ"},
    {label:"German Mark",value:"DEM",symbol:"DM"},
    {label:"Ghanaian Cedi",value:"GHS",symbol:"GH₵"},
    {label:"Gibraltar Pound",value:"GIP",symbol:"£"},
    {label:"Greek Drachma",value:"GRD",symbol:"₯, Δρχ, Δρ"},
    {label:"Guatemalan Quetzal",value:"GTQ",symbol:"Q"},
    {label:"Guinean Franc",value:"GNF",symbol:"FG"},
    {label:"Guyanaese Dollar",value:"GYD",symbol:"$"},
    {label:"Haitian Gourde",value:"HTG",symbol:"G"},
    {label:"Honduran Lempira",value:"HNL",symbol:"L"},
    {label:"Hong Kong Dollar",value:"HKD",symbol:"$"},
    {label:"Hungarian Forint",value:"HUF",symbol:"Ft"},
    {label:"Icelandic KrÃ³na",value:"ISK",symbol:"kr"},
    {label:"Indian Rupee",value:"INR",symbol:"₹"},
    {label:"Indonesian Rupiah",value:"IDR",symbol:"Rp"},
    {label:"Iranian Rial",value:"IRR",symbol:"﷼"},
    {label:"Iraqi Dinar",value:"IQD",symbol:"د.ع"},
    {label:"Israeli New Sheqel",value:"ILS",symbol:"₪"},
    {label:"Italian Lira",value:"ITL",symbol:"L,£"},
    {label:"Jamaican Dollar",value:"JMD",symbol:"J$"},
    {label:"Japanese Yen",value:"JPY",symbol:"¥"},
    {label:"Jordanian Dinar",value:"JOD",symbol:"ا.د"},
    {label:"Kazakhstani Tenge",value:"KZT",symbol:"лв"},
    {label:"Kenyan Shilling",value:"KES",symbol:"KSh"},
    {label:"Kuwaiti Dinar",value:"KWD",symbol:"ك.د"},
    {label:"Kyrgystani Som",value:"KGS",symbol:"лв"},
    {label:"Laotian Kip",value:"LAK",symbol:"₭"},
    {label:"Latvian Lats",value:"LVL",symbol:"Ls"},
    {label:"Lebanese Pound",value:"LBP",symbol:"£"},
    {label:"Lesotho Loti",value:"LSL",symbol:"L"},
    {label:"Liberian Dollar",value:"LRD",symbol:"$"},
    {label:"Libyan Dinar",value:"LYD",symbol:"د.ل"},
    {label:"Lithuanian Litas",value:"LTL",symbol:"Lt"},
    {label:"Macanese Pataca",value:"MOP",symbol:"$"},
    {label:"Macedonian Denar",value:"MKD",symbol:"ден"},
    {label:"Malagasy Ariary",value:"MGA",symbol:"Ar"},
    {label:"Malawian Kwacha",value:"MWK",symbol:"MK"},
    {label:"Malaysian Ringgit",value:"MYR",symbol:"RM"},
    {label:"Maldivian Rufiyaa",value:"MVR",symbol:"Rf"},
    {label:"Mauritanian Ouguiya",value:"MRO",symbol:"MRU"},
    {label:"Mauritian Rupee",value:"MUR",symbol:"₨"},
    {label:"Mexican Peso",value:"MXN",symbol:"$"},
    {label:"Moldovan Leu",value:"MDL",symbol:"L"},
    {label:"Mongolian Tugrik",value:"MNT",symbol:"₮"},
    {label:"Moroccan Dirham",value:"MAD",symbol:"MAD"},
    {label:"Mozambican Metical",value:"MZM",symbol:"MT"},
    {label:"Myanmar Kyat",value:"MMK",symbol:"K"},
    {label:"Namibian Dollar",value:"NAD",symbol:"$"},
    {label:"Nepalese Rupee",value:"NPR",symbol:"₨"},
    {label:"Netherlands Antillean Guilder",value:"ANG",symbol:"ƒ"},
    {label:"New Taiwan Dollar",value:"TWD",symbol:"$"},
    {label:"New Zealand Dollar",value:"NZD",symbol:"$"},
    {label:"Nicaraguan CÃ³rdoba",value:"NIO",symbol:"C$"},
    {label:"Nigerian Naira",value:"NGN",symbol:"₦"},
    {label:"North Korean Won",value:"KPW",symbol:"₩"},
    {label:"Norwegian Krone",value:"NOK",symbol:"kr"},
    {label:"Omani Rial",value:"OMR",symbol:".ع.ر"},
    {label:"Pakistani Rupee",value:"PKR",symbol:"₨"},
    {label:"Panamanian Balboa",value:"PAB",symbol:"B/."},
    {label:"Papua New Guinean Kina",value:"PGK",symbol:"K"},
    {label:"Paraguayan Guarani",value:"PYG",symbol:"₲"},
    {label:"Peruvian Nuevo Sol",value:"PEN",symbol:"S/."},
    {label:"Philippine Peso",value:"PHP",symbol:"₱"},
    {label:"Polish Zloty",value:"PLN",symbol:"zł"},
    {label:"Qatari Rial",value:"QAR",symbol:"ق.ر"},
    {label:"Romanian Leu",value:"RON",symbol:"lei"},
    {label:"Russian Ruble",value:"RUB",symbol:"₽"},
    {label:"Rwandan Franc",value:"RWF",symbol:"FRw"},
    {label:"Salvadoran ColÃ³n",value:"SVC",symbol:"₡"},
    {label:"Samoan Tala",value:"WST",symbol:"SAT"},
    {label:"Saudi Riyal",value:"SAR",symbol:"﷼"},
    {label:"Serbian Dinar",value:"RSD",symbol:"din"},
    {label:"Seychellois Rupee",value:"SCR",symbol:"SRe"},
    {label:"Sierra Leonean Leone",value:"SLL",symbol:"Le"},
    {label:"Singapore Dollar",value:"SGD",symbol:"$"},
    {label:"Slovak Koruna",value:"SKK",symbol:"Sk"},
    {label:"Solomon Islands Dollar",value:"SBD",symbol:"Si$"},
    {label:"Somali Shilling",value:"SOS",symbol:"Sh.so."},
    {label:"South African Rand",value:"ZAR",symbol:"R"},
    {label:"South Korean Won",value:"KRW",symbol:"₩"},
    {label:"Special Drawing Rights",value:"XDR",symbol:"SDR"},
    {label:"Sri Lankan Rupee",value:"LKR",symbol:"Rs"},
    {label:"St. Helena Pound",value:"SHP",symbol:"£"},
    {label:"Sudanese Pound",value:"SDG",symbol:".س.ج"},
    {label:"Surilabelse Dollar",value:"SRD",symbol:"$"},
    {label:"Swazi Lilangeni",value:"SZL",symbol:"E"},
    {label:"Swedish Krona",value:"SEK",symbol:"kr"},
    {label:"Swiss Franc",value:"CHF",symbol:"CHf"},
    {label:"Syrian Pound",value:"SYP",symbol:"LS"},
    {label:"São Tomé and Príncipe Dobra",value:"STD",symbol:"Db"},
    {label:"Tajikistani Somoni",value:"TJS",symbol:"SM"},
    {label:"Tanzanian Shilling",value:"TZS",symbol:"TSh"},
    {label:"Thai Baht",value:"THB",symbol:"฿"},
    {label:"Tongan Pa'anga",value:"TOP",symbol:"$"},
    {label:"Trinidad & Tobago Dollar",value:"TTD",symbol:"$"},
    {label:"Tunisian Dinar",value:"TND",symbol:"ت.د"},
    {label:"Turkish Lira",value:"TRY",symbol:"₺"},
    {label:"Turkmenistani Manat",value:"TMT",symbol:"T"},
    {label:"Ugandan Shilling",value:"UGX",symbol:"USh"},
    {label:"Ukrainian Hryvnia",value:"UAH",symbol:"₴"},
    {label:"United Arab Emirates Dirham",value:"AED",symbol:"إ.د"},
    {label:"Uruguayan Peso",value:"UYU",symbol:"$"},
    {label:"US Dollar",value:"USD",symbol:"$"},
    {label:"Uzbekistan Som",value:"UZS",symbol:"лв"},
    {label:"Vanuatu Vatu",value:"VUV",symbol:"VT"},
    {label:"Venezuelan BolÃvar",value:"VEF",symbol:"Bs"},
    {label:"Vietlabelse Dong",value:"VND",symbol:"₫"},
    {label:"Yemeni Rial",value:"YER",symbol:"﷼"},
    {label:"Zambian Kwacha",value:"ZMK",symbol:"ZK"}
];

export default currencies